### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Qu4tro** [guptachetan1997/Episodes#4]
Hi. I'm trying to install Episodes, but the first command fails with the following error message:

```
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: tvshow_show

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/Episodes/Episodes/urls.py", line 23, in <module>
    url(r'^', include('tvshow.urls', namespace='tvshow'))]
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/Episodes/tvshow/urls.py", line 2, in <module>
    from .views import (home, add_search, add ,single_show, episode_swt, season_swt, search, update_show, update_show_rating, recommended, update_all_continuing, delete_show)
  File "/home/user/Episodes/tvshow/views.py", line 5, in <module>
    from .utils.recommender import get_recommendations
  File "/home/user/Episodes/tvshow/utils/recommender.py", line 10, in <module>
    train_df = build_training_set()
  File "/home/user/Episodes/tvshow/utils/cts.py", line 49, in build_training_set
    for show in show_data:
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.local/share/virtualenvs/Episodes/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: tvshow_show
```

To prepare the environment, I did the following

```
git clone $thisrepo
cd Episodes
pew new Episodes # create virtualenv
pip install django sklearn requests pandas scipy # scipy is not listed as a dependency, but there was a importError without it.
```
and that's it. 

Any ideas?

**Comment by guptachetan1997** [comment]
Did you run the migrations commands as written in the README?

**Comment by Qu4tro** [comment]
I wasn't using the production branch, but I changed and it still gives the same error.

```
> git status
On branch production
Your branch is up-to-date with 'origin/production'.
nothing to commit, working tree clean
```

This error is given by the first command:
`python3 manage.py makemigrations`

**Comment by guptachetan1997** [comment]
I have made some changes and also tested in on my system. Please pull the latest production branch and try the migrations commands.

**Comment by Qu4tro** [comment]
It's fixed. Thanks.
