### ISSUE TITLE
Error on makemigrations

### ISSUE THREAD

**Issue by EntilZha** [guptachetan1997/Episodes#6]
I tried out the install directions on a fairly clean install of python 3.6 and got the error below. I am guessing there are specific version dependencies so maybe adding a `requirements.txt` or `setup.py` with version numbers would be helpful.

```
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/pedro/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/pedro/Documents/Code/Episodes/Episodes/urls.py", line 23, in <module>
    url(r'^', include('tvshow.urls', namespace='tvshow'))]
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/pedro/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/pedro/Documents/Code/Episodes/tvshow/urls.py", line 2, in <module>
    from .views import (home, add_search, add ,single_show, episode_swt, season_swt, search, update_show, update_show_rating, recommended, update_all_continuing, delete_show)
  File "/Users/pedro/Documents/Code/Episodes/tvshow/views.py", line 5, in <module>
    from .utils.recommender import get_recommendations
  File "/Users/pedro/Documents/Code/Episodes/tvshow/utils/recommender.py", line 11, in <module>
    x_train = scale(train_df.iloc[:, 5:])
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 129, in scale
    dtype=FLOAT_DTYPES)
  File "/Users/pedro/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py", line 416, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 28)) while a minimum of 1 is required by the scale function.
```

**Comment by Quantum238** [comment]
I'm getting the same error on a fresh python 3.4 install.  I agree with EntilZha's suggestion

**Comment by guptachetan1997** [comment]
I have added a requirements.txt file as you mentioned. Also have made some changes to the codebase. I have checked the code on my end and it is working. Also wanted to tell you to use the production branch.
Please try it again and notify about the result.

**Comment by Quantum238** [comment]
That pretty much worked.
I had to comment out 
pkg-resources==0.0.0

from the requirements, consistent with
http://stackoverflow.com/questions/38992194/why-does-pip-freeze-list-pkg-resources-0-0-0#comment66906396_38992194

but that was pretty easy to solve

**Comment by EntilZha** [comment]
Thanks, I pulled and switched to the production branch which seems to have fixed the issue without needing to change versions on packages. Found another lesser issue, but I'll post a new issue for that.
